global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "dapr"
    scrape_interval: 5s

    static_configs:
      - targets:
          [
            "host.docker.internal:41012",
            "host.docker.internal:41022",
            "host.docker.internal:4101",
            "host.docker.internal:4102",
          ]